name: Sync Blog Posts

on:
  push:
    paths:
      - 'pages/blog-post.html'  # Trigger when template is updated
    branches:
      - main  # or your default branch

jobs:
  sync-posts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Sync Blog Posts
      run: |
        node scripts/sync-blog-posts.js
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add blog/*/index.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync blog posts with template"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}